### ISSUE TITLE
How does this compare to Ubergraph?

### ISSUE THREAD

**Issue by bherr2** [dbmi-pitt/UBKG#1]
As I've seen this project evolve, it starts to remind me more and more of Ubergraph. How does this compare and contrast to <https://github.com/INCATools/ubergraph#integrated-obo-ontology-triplestore>?

**Comment by AlanSimmons** [comment]
No UMLS?

**Comment by computationdoc** [comment]
One answer would be see:

https://douroucouli.wordpress.com/2019/03/14/biological-knowledge-graph-modeling-design-patterns/

Another would be inclusion of UMLS and other sources that do not adhere to OBO.

Another would be UBKG is not intended for reasoning but rather translation and discovery.

Another would be the use of equivalence classes and numerical and evidence approaches.

Finally, I would say GitHub issues is not preferred location for this repository/project comparative analysis so let's please all attempt to use this repository for specifics of UBKG not to challenge its core principals which can best be discussed in its uses in the published literature coming in future. Thanks.

**Comment by bherr2** [comment]
I hope the issue wasn't taken the wrong way. I was not challenging it's core principles at all. I just see major KGs like UBKG, SPOKE, and Ubergraph coming up that have similar offerings, but are distinct in important ways (UMLS is a major differentiator for UBKG). Agree that this would be GREAT in a paper, but could also be considered for how to evolve this and other software for interoperability, reusability, etc. 

Anyway, glad to see this project moving forward in exciting ways!

(Feel free to close the issue)
