### ISSUE TITLE
Question: Properties on relationships

### ISSUE THREAD

**Issue by AlanSimmons** [dbmi-pitt/UBKG#10]
From the **data-distillery-project** Slack channel:

Properties on relationships.
It was mentioned during 
@Jonathan Silverstein's presentation in October that we plan to utilize relationship properties, but those probably include only edges, ie. relationships between concepts. Can we clarify how we plan to model it.
Moreover, there are many relationships between concepts and associated nodes that have no properties. This means our graph is basically non -weighted and we are missing important and useful feature of neo4j.

**Comment by AlanSimmons** [comment]
This is still a work in progress. To date, the relationships from assertions that have been added to the UBKG have not had properties other than that of the SAB of the ontology of provenance. For example, if the ingest file showed an assertion 

UNIPROTKB X | gene_product | HGNC HGNC:Y

Then the framework assigns the property SAB: "UNIPROTKB" to the gene_product relationship. 

We should be able to assign other properties to a relationship, using the neo4j admin-import tool and the CSV files that the framework generates. I state "should be able" because I have not yet imported relationships with properties into the graph--only nodes with properties. It might be as simple as setting up the proper columns in a file and using the --relationships parameter.

**Comment by computationdoc** [comment]
All edges among concepts have properties. For distillery so far these include the source and the evidence (not yet fully implemented as Alan points out but easily done - these is issue for that). These can be used exactly for the weighting purposes as noted and the technology would allow many others subject to standardization by CFDE KG Working Group or other forums or individual uses. Some other edges have properties in the graph to enable translation, but those are incidental to this question per se other than, yes, a property graph, not just RDF triples (per se) is needed.
