### ISSUE TITLE
General comment regarding graph base model

### ISSUE THREAD

**Issue by AlanSimmons** [dbmi-pitt/UBKG#14]
General comment regarding graph base model: it is recommended that nodes should be considered as nouns, relationships as verbs, properties on nodes as adjectives and properties on relationships as adverbs. Labels should help classify nodes.
It is reasonable to introduce new ideas and model our domain in a little different way, but in my opinion once we submit a concept, there are many associated nodes and relationships that break these recommendations.
Also, a good rule of thumb to decide if a graph model is ok is to think “can I apply shortest path algorithm somehow and get useful result?”. In our case shortest path would make sense only between concepts, but even if we apply it to concept-only subgraph, there will not be enough info without associated nodes to make any useful connection.
This all sounds like relational database way of thinking applied to graph database. I hope we can make some clarification during next week’s meeting.

**Comment by AlanSimmons** [comment]
> General comment regarding graph base model: it is recommended that nodes should be considered as nouns, relationships as verbs, properties on nodes as adjectives and properties on relationships as adverbs. Labels should help classify nodes.

This is the case now. There are nodes (nouns) for:

- Codes (in the source ontology)
- Concepts (CUIs)
- Terms
- Definitions
![image](https://user-images.githubusercontent.com/10928372/203095739-d469107b-1b3f-485a-a132-f6d9f5dc0323.png)

There are relationships (verbs) of many types, including:
- hierarchical (isa, inverse_isa)
- non-hierarchical

Nodes have properties (adjectives), such as SAB and CODE

Relationships have properties (adverbs)--currently, SAB.

Labels (Term and Definition nodes) classify Code nodes.

**Comment by AlanSimmons** [comment]
> Also, a good rule of thumb to decide if a graph model is ok is to think “can I apply shortest path algorithm somehow and get useful result?”. In our case shortest path would make sense only between concepts, but even if we apply it to concept-only subgraph, there will not be enough info without associated nodes to make any useful connection.

I use shortestpath algorithms all the time without an issue. I'll leave to @computationdoc  the discussion of shortest paths involving relationships.

**Comment by AlanSimmons** [comment]
> This all sounds like relational database way of thinking applied to graph database. 

I have to disagree with this. The use of path algorithms allows for knowledge discovery, which is really hard to do deterministically with a relational database. Many is the time when I have discovered relationships between concepts that I did not consider before.

**Comment by computationdoc** [comment]
This description of general best practice approaches for use of graph databases (really property graphs best practice) is precisely how this is constructed as Alan outlined.
