### ISSUE TITLE
HuBMAP/SenNet: Endpoint to return primary/derived/lab_derived status of data types

### ISSUE THREAD

**Issue by shirey** [dbmi-pitt/ubkg#57]

**Comment by AlanSimmons** [comment]
@shirey @maxsibilla 

# Statement of request
What are the values of relevant properties for a dataset data type?

# Analysis
The data_type of a dataset entity is a property determined at ingestion. Datasets of a data_type share a number of properties, including:

- dataset order: whether a primary or derived dataset
- provider: whether IEC or External Provider (lab-processed)

Both the data_type and its properties are represented in the HuBMAP and SenNet application ontologies by means of _property nodes_ and relationships that link property nodes with Dataset nodes. In particular,

- Each dataset is a node in the *HuBMAP Dataset* hierarchy.
- A dataset node links to a subclass of the *Dataset Data Type* node by means of the _has_datatype_ relationship.
- A dataset node links to a subclass of the *Dataset Provider* node by means of the _has_provider_ relationship.

For example, 

- a "Bulk RNA-Seq" dataset in HuBMAP has a data_type of _bulk-RNA_; is a primary dataset; and has the HuBMAP IEC as a provider.
- a "Bulk RNA-seq [Salmon]" dataset in HuBMAP has a data_type of _salmon_rnaseq_bulk_; is a derived dataset; and has the HUBMAP IEC as a dataset provider.
- a "seqFISH [Lab Processed]" dataset in HUBMAP has a data_type of seqFish_lab_processed; is a primary dataset; and has an External Provider as a dataset provider.

# Proposed solution
GET endpoint: dataset_properties

## parameters

- application (SenNet or HubMAP)
- strings that correspond to a list of data_types, with the default of the empty string requesting information on all data_types

## example URL
https://ontology.api.hubmapconsortium.org/dataset_properties?context=HM&data_types=bulk-RNA%2CseqFish_lab_processed
_(list of values would be separated by commas that would be URL-encoded with %2C)_

https://ontology.api.hubmapconsortium.org/dataset_properties?context=SN 
_(default returns information on all values of data_type in ontology_)

## minimum response:
array with the following information on each requested data_type:

- data_type
- Dataset Display Name (as displayed in Portal)
- Dataset order (Primary Dataset or Derived Dataset)
- Dataset Provider (HuBMAP IEC, SenNet IEC, or External Provider)

**Comment by AlanSimmons** [comment]
# Cypher query

The following query essentially replicates the content of the current assay_types.yaml file, with the addition of the dataset provider (HuBMAP IEC or External provider--i.e., lab-processed). 

This queries the HUBMAP ontology, but the SENNET version is almost identical.

// Find matching data_types for the specified application context and data_type string  

CALL  
{  
MATCH (cDataType:Code)<-[:CODE]-(pDataType:Concept)<-[isa]-(pDT:Concept)-[:CODE]->(cDT:Code)-[:PT]->(tDT:Term) WHERE cDataType.SAB = 'HUBMAP' AND cDataType.CODE='C004001' RETURN pDT.CUI AS data_typeCUI, tDT.name AS data_type  
}  
//Find Dataset nodes linked to the data_type.  
CALL  
{  
WITH data_typeCUI  
MATCH (pDataType:Concept)<-[r:has_data_type]-(pDataset:Concept)  
WHERE r.SAB = 'HUBMAP'  
AND pDataType.CUI=data_typeCUI  
RETURN pDataset.CUI AS DatasetCUI  
}  
//Find Dataset Display Name nodes linked to the Dataset nodes.  
CALL 
{ 
WITH DatasetCUI  
OPTIONAL MATCH (pDataset:Concept)-[rProperty:has_display_name]->(pProperty:Concept)-[:CODE]->(cProperty:Code)-[:PT]->(tProperty:Term)  
WHERE cProperty.SAB='HUBMAP' AND rProperty.SAB='HUBMAP'  
AND pDataset.CUI=DatasetCUI  
RETURN tProperty.name AS display_name  
} 
//Find Dataset Provider nodes linked to the Dataset nodes 
CALL 
{ 
WITH DatasetCUI 
OPTIONAL MATCH (pDataset:Concept)-[rProperty:provided_by]->(pProperty:Concept)-[:CODE]->(cProperty:Code)-[:PT]->(tProperty:Term)  
WHERE cProperty.SAB='HUBMAP' AND rProperty.SAB='HUBMAP'  
AND pDataset.CUI=DatasetCUI  
RETURN tProperty.name AS dataset_provider  
} 
//Find Dataset Order nodes (subclasses of Dataset Order node) 
CALL 
{ 
MATCH (cDatasetOrder:Code)<-[:CODE]-(pDatasetOrder:Concept)<-[:isa]-(pOrder:Concept) 
WHERE cDatasetOrder.SAB = 'HUBMAP' AND cDatasetOrder.CODE='C004002' 
RETURN pOrder.CUI AS pOrderCUI 
} 
//Find Dataset order nodes for Datasets 
CALL 
{ 
WITH DatasetCUI,pOrderCUI 
MATCH (pDataset:Concept)-[rProperty:isa]->(pProperty:Concept)-[:CODE]->(cProperty:Code)-[:PT]->(tProperty:Term) 
WHERE cProperty.SAB='HUBMAP' AND rProperty.SAB='HUBMAP' 
AND pDataset.CUI=DatasetCUI  
AND pProperty.CUI IN pOrderCUI 
RETURN DISTINCT tProperty.name AS dataset_order 
} 
//Find 'contains-pii' for datasets 
CALL 
{ 
WITH DatasetCUI 
OPTIONAL MATCH (pDataset:Concept)-[rProperty:contains]->(pProperty:Concept)-[:CODE]->(cProperty:Code)-[:PT]->(tProperty:Term) 
WHERE cProperty.SAB='HUBMAP' AND cProperty.CODE='C004009' AND rProperty.SAB='HUBMAP' 
AND pDataset.CUI=DatasetCUI 
RETURN tProperty.name IS NOT NULL AS contains_pii 
} 
//Find 'alt-names' for datasets, which is linked to the datatype 
CALL 
{ 
WITH data_typeCUI 
OPTIONAL MATCH (pDataType:Concept)-[:CODE]->(cDataType:Code)-[:SY]->(tSyn:Term) 
WHERE cDataType.SAB='HUBMAP' 
AND pDataType.CUI=data_typeCUI  
RETURN COLLECT(tSyn.name) AS alt_names 
} 
//Find 'vitessce-hints' for datasets, which is linked to the datatype 
CALL 
{ 
WITH data_typeCUI 
OPTIONAL MATCH (pDataType:Concept)-[r:has_vitessce_hint]->(pVitessceHint:Concept)-[:CODE]->(cVitessceHint:Code)-[:PT]->(tVitessceHint:Term) 
WHERE cVitessceHint.SAB='HUBMAP' and r.SAB='HUBMAP' 
AND pDataType.CUI=data_typeCUI  
RETURN COLLECT(tVitessceHint.name) AS vitessce_hints 
} 
//Ordered output 
WITH data_type,display_name,alt_names,dataset_order,dataset_provider,contains_pii,vitessce_hints 
RETURN data_type,display_name,alt_names,dataset_order,dataset_provider,contains_pii,vitessce_hints 
ORDER BY data_type

**Comment by AlanSimmons** [comment]
# JSON response
The JSON returned from the endpoint will be a JSON array similar to the following:

```
[
  {
    "alt-names": [],
    "contains-pii": false,
    "data_type": "AF",
    "dataset_provider": "HuBMAP IEC",
    "description": "Autofluorescence Microscopy",
    "primary": true,
    "vis-only": false,
    "vitessce-hints": []
  },
...
]
```
