### ISSUE TITLE
Duplicate  `POST /assayname` endpoint

### ISSUE THREAD

**Issue by shirey** [dbmi-pitt/ubkg#67]
Create a new endpoint that exactly duplicates the functionality (exact inputs/outputs) of HuBMAP Search API [POST /assayname](https://github.com/hubmapconsortium/search-api/blob/db5c5aca6d1f0b0716f7c0ba608a4ca25b158bd3/src/libs/hubmap_endpoints.py#L12) endpoint by pulling all information from the SenNet/HuMAP application specific ontologies (instead of the assay_types.yaml file).

**Comment by AlanSimmons** [comment]
@shirey Can we close this?
