### ISSUE TITLE
Update current organ types for SenNet

### ISSUE THREAD

**Issue by maxsibilla** [dbmi-pitt/ubkg#73]
In regards to the values returned by https://ontology.api.hubmapconsortium.org/valueset?parent_sab=SENNET&parent_code=C000008&child_sabs=SENNET

Currently the only organs that are supported in the portal are: "Adipose", "Blood", "Brain", "Breast", "Large Intestine", "Liver", "Lung (Left)", "Lung (Right)", "Lymph Node", "Kidney (Left)", "Kidney (Right)", "Muscle", "Ovary (Left)", "Ovary (Right)", "Skin", "Other"

- "Lymph Node" is new and missing from this API response
- "Ovary (Left)" is missing
- "Blood", "Liver", and "Skin" have a space at the end of the "term" value
- "Brain",  "Kidney", "Muscle", and "Skin" are duplicated
- I don't believe we support "biopsy"

**Comment by AlanSimmons** [comment]
Closed and moved to ubkg-etl.
