### ISSUE TITLE
Question about mandatory reverse relationships between concepts

### ISSUE THREAD

**Issue by AlanSimmons** [dbmi-pitt/UBKG#8]
From the #data-distillery-project Slack:
This was partially mentioned during last meeting, but I would like to emphasize this issue. Please reconsider if reverse relationships are really necessary. They would make sense if they brought additional info to the graph, but if they are added purely because we want both directions, then it doesnt make sense. Neo4j can query equally well both up and downstream of relationship direction.
Please clarify, maybe I am missing something?

**Comment by computationdoc** [comment]
Both directions are necessary for multiple reasons. One, they allow forward query from a concept to all its relationships which is highly efficient in algorithms. Two, UMLS provides then already. Three, there are some relationships that are equivalent in both directions such as co-occurrence which can be distinguished via counting of bidirectional is allowed. There are some other detailed issues in relationship to no inward relationships to concepts from node types other than concepts that enable graph algorithm performance also - to much to explain here.

Please do not use this repository to question core principles of UBKG. These will best be addressed in future publications in the peer-reviewed literature. Thank you.
